app:
  name: admin
  description: "admin模块"
  version: 1.0.0
  port: 7001
  prefix: "/admin"
  enableCors: true

doc:
  enable: true

logger:
  level: info
  zippedArchive: true
  maxSize: 20m
  maxFiles: 30D
  lokiHost: "http://127.0.0.1:3100"
  transports:
    - "console"
    - "file"
    - "loki"

tempo:
  enabled: true
  otlpHttpUrl: "http://127.0.0.1:4318"

prometheus:
  enabled: true
  path: "/metrics"

syncStorage:
  storage:
    middlewareKeys:
      - "token"
    guardKeys:
      - "page"
